"""delete_avatar

Revision ID: 91d49fd427da
Revises: f72a92a01c0f
Create Date: 2023-07-31 16:34:22.834112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d49fd427da'
down_revision = 'f72a92a01c0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
