"""initial

Revision ID: f72a92a01c0f
Revises: 
Create Date: 2023-07-31 16:26:33.259882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72a92a01c0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_user', sa.String(), nullable=True),
    sa.Column('second_user', sa.String(), nullable=True),
    sa.Column('have_dialog', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_to_user_first_user'), 'user_to_user', ['first_user'], unique=False)
    op.create_index(op.f('ix_user_to_user_second_user'), 'user_to_user', ['second_user'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('from_user', sa.String(), nullable=True),
    sa.Column('to_user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.username'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_to_user_second_user'), table_name='user_to_user')
    op.drop_index(op.f('ix_user_to_user_first_user'), table_name='user_to_user')
    op.drop_table('user_to_user')
    # ### end Alembic commands ###
